### ISSUE TITLE
After Adding Veriff CocoaPod we receive Invalid Bundle on app submission to iTunes Connect

### ISSUE THREAD

**Issue by dimaosa** [Veriff/veriff-sample-ios#11]
Hi there, 

We added Veriff CocoaPod to the project and uploaded to TestFlight, after that we received the following error:
![2019-10-29_09-46-25](https://user-images.githubusercontent.com/8642157/67747579-b6e03800-fa31-11e9-883c-ad53585be5d4.png)

CocoaPod -> `pod 'VeriffSDK', '2.5.0-patch3'`

This could be caused when your lib Project Settings -> `Code Coverage` is turned on.

**Correct state**:
![2019-10-29_11-30-51](https://user-images.githubusercontent.com/8642157/67754816-bfd80600-fa3f-11e9-823f-f36730409799.png)

**Incorrect state**:
![2019-10-29_11-31-25](https://user-images.githubusercontent.com/8642157/67754827-c36b8d00-fa3f-11e9-8c8f-1a9fa4651f7a.png)

**Comment by dimaosa** [comment]
@kristjanpirnpuu @lauriesk @MertCelik

**Comment by MertCelik** [comment]
Hi @dimaosa , we really appreciate your patience on this. We have just released version 2.6.1 including this fix.

Also we moved our communications and documentations to [https://developers.veriff.com/](https://developers.veriff.com/). Next time if you kindly contact us through there, we will be much faster to react 💪

**Comment by dimaosa** [comment]
Thanks, @MertCelik , and follow up question, does version 2.6.1 compatible with Swift 5.1.2?

**Comment by dimaosa** [comment]
Thanks @MertCelik
