### ISSUE TITLE
UI ignores document.type

### ISSUE THREAD

**Issue by domasn** [Veriff/veriff-sample-ios#2]
Veriff version: `2.0.3`

When creating a session with a POST to `/sessions` we specify document type as described in the [docs](https://developers.veriff.me):
> type: (one of PASSPORT, ID_CARD, DRIVERS_LICENSE, RESIDENCE_PERMIT)
Document type

Nevertheless, after user selects country of document he is promted to select the document type:

![Screenshot 2019-03-12 at 13 46 00](https://user-images.githubusercontent.com/7569279/54197575-f5d67300-44cc-11e9-9804-995c5dda17b7.png)

This results with `/webhooks /decision` that has a `document.type` mismatching the one sent to `/session`

**Comment by kristjanpirnpuu** [comment]
This feature will be implemented in one of upcoming releases.

**Comment by kristjanpirnpuu** [comment]
Target is 2.3.0 release on 23rd of May

**Comment by kristjanpirnpuu** [comment]
Veriff SDK 2.3.0 is released. Closing issue.
