### ISSUE TITLE
Module compiled with Swift 5.0 cannot be imported by the Swift 5.1 compiler

### ISSUE THREAD

**Issue by nicolla1003** [Veriff/veriff-sample-ios#9]
When using Veriff in newest Xcode 11, I get the error:
Module compiled with Swift 5.0 cannot be imported by the Swift 5.1 compiler.

_Swift 5.0 does provide ABI stability, but that alone is not enough to ship pre-compiled libraries. You also need module stability so that different versions of the Swift compiler can understand the public API interface to your library, which is not available in Swift 5.0. Please see the Swift blog for more details.
https://swift.org/blog/abi-stability-and-more/_

Are you planning to fix this soon?
@kristjanpirnpuu @lauriesk @MertCelik

**Comment by MertCelik** [comment]
Hey @nicolla1003!

Thank you for reaching out on this! We are currently working on structuring bleeding edge builds but meanwhile we pushed some builds that is compatible of Xcode 11. Could you please use the version below for that?

`pod 'VeriffSDK', '2.5.0-patch3'`

**Comment by nicolla1003** [comment]
It's working. Thx again.
